name: Publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - released

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build/publish Docs
    if: github.repository == 'docling-project/docling-java'
    steps:
      - name: Checkout sources
        if: github.event_name != 'release'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          path: app

      - name: Get release sources
        if: github.event_name == 'release'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          path: app

      - name: Setup env (release)
        if: github.event_name == 'release'
        working-directory: app
        run: |
          echo "DOCS_ALIAS=current" >> $GITHUB_ENV
          echo "DOCS_VERSION=$(yq '.release.previous-version' .github/project.yml)" >> $GITHUB_ENV

      - name: Setup env (other)
        if: (github.event_name != 'release')
        working-directory: app
        run: |
          echo "DOCS_ALIAS=dev" >> $GITHUB_ENV
          echo "DOCS_VERSION=$(yq '.release.current-version' .github/project.yml)" >> $GITHUB_ENV

      - name: Get docs
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: gh-pages
          path: docs

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.x'

      - name: Setup Java 21
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Show current docs
        run: |
          tree ${{ github.workspace }}/docs
          cat ${{ github.workspace }}/docs/versions.json

      - name: Generate documentation
        working-directory: app
        run: |
          ./gradlew --console=plain :docs:build \
            -Pversion=${{ env.DOCS_VERSION }} \
            -Pdocs.alias=${{ env.DOCS_ALIAS }} \
            -Pdocs.versionsFile=${{ github.workspace }}/docs/versions.json

      - name: Copy to gh-pages
        run: cp -Rf app/docs/build/mkdocs/* docs/

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ vars.DOCLING_JAVA_CI_APP_ID }}
          private-key: ${{ secrets.DOCLING_JAVA_CI_PRIVATE_KEY }}

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          path: docs
          commit-message: "docs: Build and publish docs (from ${{ github.workflow }} run # ${{ github.run_number }})"
          branch: build-docs/sourceref
          branch-suffix: short-commit-hash
          delete-branch: true
          base: gh-pages
          signoff: true
          sign-commits: true
          title: "docs: Build and publish docs (from ${{ github.workflow }} run # ${{ github.run_number }})"
          body: "docs: Build and publish docs from [${{ github.workflow }} run # ${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}), which was triggered by commit ${{ env.REF }}."
          labels: documentation

      - name: Merge PR
        if: (steps.create-pr.outputs.pull-request-operation == 'created') && steps.create-pr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr merge --merge --admin --delete-branch "${{ steps.create-pr.outputs.pull-request-url }}"
